AWSTemplateFormatVersion: 2010-09-09
Transform:
- AWS::Serverless-2016-10-31
- AWS::CodeStar

Parameters:
  ProjectId:
    Type: String
    Description: AWS CodeStar projectID used to associate new resources to team members

Resources:
  DetectImage:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.rahulspace.products.media.image.ImageDetector
      CodeUri: ./target/ImageDetector-1.0.jar
      Runtime: java8
      Role:
        Fn::ImportValue:
          !Join ['-', [!Ref 'ProjectId', !Ref 'AWS::Region', 'LambdaTrustRole']]
      Events:
        GetEvent:
          Type: S3
          Properties:
            Path: /java